 $(document).ready(function(){
    $('.sidenav').sidenav();
    //Paralax
    $('.parallax').parallax();
    //carousel
    $('.carousel').carousel();
    //collapsible
    $('.collapsible').collapsible();
 });